#Requires -Version 7.0
<#
.SYNOPSIS
  Proves a plugin generated by the existing deterministic PluginBuilder can be
  installed and activated in a real, disposable WordPress environment.

.DESCRIPTION
  PluginSpec -> existing API build endpoint -> generated ZIP -> disposable
  Docker WordPress -> php -l -> wp plugin install -> wp plugin activate ->
  verify active -> destroy containers.

  This script does not reimplement plugin generation. It starts the existing
  ASP.NET Core API and POSTs a known PluginSpec to the existing
  POST /api/plugins/build endpoint, using the ZIP that endpoint returns.

  All Docker/WP-CLI commands run synchronously via the call operator (&).
  Only the API process runs as a background Process object, because it must
  keep running while the rest of this script executes.

.EXAMPLE
  powershell -ExecutionPolicy Bypass -File scripts/Validate-GeneratedPlugin.ps1
#>

$ErrorActionPreference = "Stop"

$RepoRoot = Split-Path -Parent $PSScriptRoot
$ApiProject = Join-Path $RepoRoot "src/WPAIPlugin.Api"
$ApiDll = Join-Path $ApiProject "bin/Debug/net8.0/WPAIPlugin.Api.dll"
$ComposeFile = Join-Path $RepoRoot "docker/docker-compose.validate.yml"
$ValidationPort = 5999
$ApiBaseUrl = "http://127.0.0.1:$ValidationPort"
$ComposeProjectName = "wpaiplugin-validate"

$TempDir = Join-Path ([System.IO.Path]::GetTempPath()) ("wpaiplugin-validate-" + [Guid]::NewGuid().ToString("N"))
$ZipPath = Join-Path $TempDir "plugin.zip"

$script:ApiProcess = $null
$script:DockerStarted = $false
$ExitCode = 1

try {
    # [1/5] Starting API
    Write-Host "[1/5] Starting API"

    Write-Host "Building API (dotnet build src/WPAIPlugin.Api -c Debug)"
    & dotnet build $ApiProject -c Debug
    if ($LASTEXITCODE -ne 0) {
        throw "dotnet build failed with exit code $LASTEXITCODE"
    }
    if (-not (Test-Path $ApiDll)) {
        throw "Built API DLL not found at $ApiDll"
    }

    New-Item -ItemType Directory -Path $TempDir -Force | Out-Null
    $apiStdOut = Join-Path $TempDir "api-stdout.log"
    $apiStdErr = Join-Path $TempDir "api-stderr.log"

    $env:ASPNETCORE_URLS = $ApiBaseUrl
    $env:ASPNETCORE_ENVIRONMENT = "Development"
    $script:ApiProcess = Start-Process -FilePath "dotnet" `
        -ArgumentList @("`"$ApiDll`"") `
        -PassThru -WindowStyle Hidden `
        -RedirectStandardOutput $apiStdOut `
        -RedirectStandardError $apiStdErr

    Write-Host "API process started (PID $($script:ApiProcess.Id)). Waiting for it to respond on $ApiBaseUrl ..."
    $apiReady = $false
    for ($attempt = 1; $attempt -le 30; $attempt++) {
        if ($script:ApiProcess.HasExited) {
            break
        }
        try {
            $resp = Invoke-WebRequest -Uri "$ApiBaseUrl/" -TimeoutSec 2 -SkipHttpErrorCheck
            if ($resp.StatusCode -gt 0) { $apiReady = $true; break }
        } catch {
            # Not ready yet; keep polling.
        }
        Write-Host "Waiting for API... attempt $attempt/30"
        Start-Sleep -Seconds 1
    }

    if (-not $apiReady) {
        Write-Host "---- API stdout ----"
        if (Test-Path $apiStdOut) { Get-Content $apiStdOut | Write-Host }
        Write-Host "---- API stderr ----"
        if (Test-Path $apiStdErr) { Get-Content $apiStdErr | Write-Host }
        throw "API did not become ready within timeout."
    }

    # [2/5] Building plugin
    Write-Host "[2/5] Building plugin"

    $pluginSpec = @{
        name        = "Validation Plugin"
        slug        = "validation-plugin"
        description = "Deterministic plugin exercising all current generator features."
        version     = "1.0.0"
        author      = "WPAI Plugin Builder"
        features    = @("shortcode", "custom-post-type", "settings-page", "custom-fields", "scheduled-task")
        customPostType = @{
            singularName = "Validation Item"
            pluralName   = "Validation Items"
            slug         = "validation-item"
            public       = $true
            hasArchive   = $false
        }
        settingsPage = @{
            pageTitle = "Validation Settings"
            menuTitle = "Validation"
            fields    = @(
                @{ key = "api_key"; label = "API Key"; type = "text"; defaultValue = "" }
                @{ key = "notes"; label = "Notes"; type = "textarea" }
                @{ key = "enabled"; label = "Enabled"; type = "checkbox"; defaultValue = "1" }
            )
        }
        customFields = @{
            postType = "validation-item"
            fields   = @(
                @{ key = "detail"; label = "Detail"; type = "text" }
            )
        }
        scheduledTask = @{
            taskName = "Validation Cleanup"
            schedule = "daily"
            hookName = "validation_plugin_cleanup"
        }
    } | ConvertTo-Json -Depth 10

    Write-Host "Requesting plugin ZIP from POST /api/plugins/build"
    Invoke-WebRequest -Uri "$ApiBaseUrl/api/plugins/build" -Method Post `
        -ContentType "application/json" -Body $pluginSpec `
        -OutFile $ZipPath -TimeoutSec 30

    if (-not (Test-Path $ZipPath) -or (Get-Item $ZipPath).Length -eq 0) {
        throw "Build endpoint did not return a usable ZIP."
    }
    Write-Host "Saved: $ZipPath"

    $ExtractDir = Join-Path $TempDir "extracted"
    Expand-Archive -Path $ZipPath -DestinationPath $ExtractDir -Force
    $PluginFolder = Get-ChildItem -Path $ExtractDir -Directory | Select-Object -First 1
    if (-not $PluginFolder) {
        throw "Generated ZIP did not contain a plugin folder."
    }
    $PluginSlug = $PluginFolder.Name

    # [3/5] Starting WordPress
    Write-Host "[3/5] Starting WordPress"

    & docker compose -p $ComposeProjectName -f $ComposeFile up -d
    if ($LASTEXITCODE -ne 0) {
        throw "docker compose up failed with exit code $LASTEXITCODE"
    }
    $script:DockerStarted = $true

    $dbReady = $false
    for ($attempt = 1; $attempt -le 30; $attempt++) {
        Write-Host "Waiting for database... attempt $attempt/30"
        & docker compose -p $ComposeProjectName -f $ComposeFile exec -T db healthcheck.sh --connect --innodb_initialized 2>$null
        if ($LASTEXITCODE -eq 0) { $dbReady = $true; break }
        Start-Sleep -Seconds 1
    }
    if (-not $dbReady) {
        & docker compose -p $ComposeProjectName -f $ComposeFile ps
        & docker compose -p $ComposeProjectName -f $ComposeFile logs db
        throw "Database did not become ready within timeout."
    }

    $wpReady = $false
    for ($attempt = 1; $attempt -le 30; $attempt++) {
        Write-Host "Waiting for WordPress core files... attempt $attempt/30"
        & docker compose -p $ComposeProjectName -f $ComposeFile exec -T wpcli test -f /var/www/html/wp-load.php
        if ($LASTEXITCODE -eq 0) { $wpReady = $true; break }
        Start-Sleep -Seconds 1
    }
    if (-not $wpReady) {
        & docker compose -p $ComposeProjectName -f $ComposeFile ps
        & docker compose -p $ComposeProjectName -f $ComposeFile logs wordpress
        throw "WordPress core files were not ready within timeout."
    }

    # [4/5] Validating plugin
    Write-Host "[4/5] Validating plugin"

    # Copy the generated plugin artefact into the wpcli container. Only this
    # generated ZIP/its extracted contents are copied in - no host mount.
    $containerId = (& docker compose -p $ComposeProjectName -f $ComposeFile ps -q wpcli).Trim()
    if (-not $containerId) {
        throw "Could not resolve wpcli container id."
    }

    & docker cp $ZipPath "${containerId}:/tmp/plugin.zip"
    if ($LASTEXITCODE -ne 0) { throw "docker cp of plugin ZIP failed with exit code $LASTEXITCODE." }

    & docker cp "$ExtractDir/." "${containerId}:/tmp/lint"
    if ($LASTEXITCODE -ne 0) { throw "docker cp of extracted plugin failed with exit code $LASTEXITCODE." }

    # 1. PHP lint of every generated PHP file.
    $phpFiles = Get-ChildItem -Path $ExtractDir -Recurse -Filter *.php
    if ($phpFiles.Count -eq 0) {
        throw "Generated plugin contained no PHP files to lint."
    }
    foreach ($file in $phpFiles) {
        $relative = $file.FullName.Substring($ExtractDir.Length).TrimStart('\', '/').Replace('\', '/')
        Write-Host "php -l /tmp/lint/$relative"
        & docker compose -p $ComposeProjectName -f $ComposeFile exec -T wpcli php -l "/tmp/lint/$relative"
        if ($LASTEXITCODE -ne 0) {
            throw "PHP syntax error in $relative (php -l exit code $LASTEXITCODE)."
        }
    }
    Write-Host "All $($phpFiles.Count) PHP file(s) passed php -l."

    # 2. WordPress installation/setup if required.
    & docker compose -p $ComposeProjectName -f $ComposeFile exec -T wpcli wp core is-installed --allow-root
    if ($LASTEXITCODE -ne 0) {
        Write-Host "Installing WordPress (wp core install)"
        & docker compose -p $ComposeProjectName -f $ComposeFile exec -T wpcli wp core install `
            --url="http://validation.local" `
            --title="Validation Site" `
            --admin_user=validate_admin `
            --admin_password=validate-admin-pw `
            --admin_email=validate@example.test `
            --skip-email --allow-root
        if ($LASTEXITCODE -ne 0) {
            throw "wp core install failed with exit code $LASTEXITCODE."
        }
    }

    # 3. wp plugin install <zip>
    Write-Host "wp plugin install /tmp/plugin.zip"
    & docker compose -p $ComposeProjectName -f $ComposeFile exec -T wpcli wp plugin install /tmp/plugin.zip --allow-root
    if ($LASTEXITCODE -ne 0) {
        throw "wp plugin install failed with exit code $LASTEXITCODE."
    }

    # 4. wp plugin activate <slug>
    Write-Host "wp plugin activate $PluginSlug"
    & docker compose -p $ComposeProjectName -f $ComposeFile exec -T wpcli wp plugin activate $PluginSlug --allow-root
    if ($LASTEXITCODE -ne 0) {
        throw "wp plugin activate failed with exit code $LASTEXITCODE."
    }

    # 5. wp plugin is-active <slug>
    Write-Host "wp plugin is-active $PluginSlug"
    & docker compose -p $ComposeProjectName -f $ComposeFile exec -T wpcli wp plugin is-active $PluginSlug --allow-root
    if ($LASTEXITCODE -ne 0) {
        throw "Plugin '$PluginSlug' is not active."
    }

    Write-Host "[5/5] Cleaning up"
    Write-Host "PASS: Plugin installed and activated successfully."
    $ExitCode = 0
}
catch {
    Write-Host "FAIL: $($_.Exception.Message)"
    $ExitCode = 1
}
finally {
    if ($script:DockerStarted) {
        try {
            & docker compose -p $ComposeProjectName -f $ComposeFile down -v --remove-orphans
        } catch {
            Write-Host "Cleanup warning: docker compose down failed: $($_.Exception.Message)"
        }
    }

    if ($script:ApiProcess -and -not $script:ApiProcess.HasExited) {
        try {
            & taskkill /PID $script:ApiProcess.Id /T /F 2>&1 | Out-Null
        } catch {
            Write-Host "Cleanup warning: failed to stop API process: $($_.Exception.Message)"
        }
    }

    try {
        $stillListening = Get-NetTCPConnection -LocalPort $ValidationPort -State Listen -ErrorAction SilentlyContinue
        if ($stillListening) {
            Write-Host "Cleanup warning: port $ValidationPort is still listening after cleanup (PID $($stillListening.OwningProcess -join ','))."
        }
    } catch {
        # Get-NetTCPConnection may be unavailable in some environments; not fatal.
    }

    if (Test-Path $TempDir) {
        try {
            Remove-Item -Path $TempDir -Recurse -Force -ErrorAction Stop
        } catch {
            Write-Host "Cleanup warning: failed to delete $TempDir : $($_.Exception.Message)"
        }
    }
}

exit $ExitCode
